[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

# Remappings for OpenZeppelin Contracts Upgradeable v5
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Optimizer settings
optimizer = true
optimizer_runs = 1
via_ir = true

# Testing settings
fuzz = { runs = 256 }
invariant = { runs = 256 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
